version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
    networks:
      - backend
    ports:
      - $PORTAINER_PORT:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $OMV2_DIR/appdata/portainer:/data
    command: -H unix:///var/run/docker.sock

networks:
  backend:
    name: backend
    driver: bridge